jobs/urls.py
from django.urls import path
from rest_framework import routers

from .views import (
    IndexView,
    JobCreateView,
    JobDetailView,
    JobListView,
    JobUpdateView,
    JobViewSet,
    RideCreateView,
    RideDetailView,
    RideListView,
    CustomerCreateView,
    CustomerUpdateView,
    CustomerDetailView,
    CustomerListView,
    LightCreateView,
    LightDetailView,
    LightListView,
    RideUpdateView,
    ImageCreateView,
    add_customer_rides,
)

router = routers.SimpleRouter()
router.register("jobs", JobViewSet)


urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("job/<int:pk>", JobDetailView.as_view(), name="detail_job"),
    path("job/<int:pk>/update", JobUpdateView.as_view(), name="update_job"),
    path("jobs", JobListView.as_view(), name="list_jobs"),
    path("job/new", JobCreateView.as_view(), name="create_job"),
    path("ride/<int:pk>", RideDetailView.as_view(), name="detail_ride"),
    path("ride/<int:pk>/update", RideUpdateView.as_view(), name="update_ride"),
    path("rides", RideListView.as_view(), name="list_rides"),
    path("ride/new", RideCreateView.as_view(), name="create_ride"),
    path("customer/<int:pk>", CustomerDetailView.as_view(), name="detail_customer"),
    path(
        "customer/<int:pk>/update", CustomerUpdateView.as_view(), name="update_customer"
    ),
    path("customers", CustomerListView.as_view(), name="list_customers"),
    path("customer/new", CustomerCreateView.as_view(), name="create_customer"),
    path("customer/rides/<int:pk>", add_customer_rides, name="add_customer_rides"),
    path("light/<int:pk>", LightDetailView.as_view(), name="detail_light"),
    path("lights", LightListView.as_view(), name="list_lights"),
    path("light/new", LightCreateView.as_view(), name="create_light"),
    path("upload/", ImageCreateView.as_view(), name="upload_image"),
]

leddocs/urls.py
import debug_toolbar
from rest_framework import routers
from django.contrib import admin
from django.urls import path, include
from jobs.urls import router as job_router

router = routers.DefaultRouter()
router.registry.extend(job_router.registry)


urlpatterns = [
    path("admin/", admin.site.urls),
    path("grappelli/", include("grappelli.urls")),
    path("", include("jobs.urls")),
    path("__debug__/", include(debug_toolbar.urls)),
    path("api/v1/", include(router.urls)),
]

jobs/models.py
from django.db import models
from django.urls import reverse


class Job(models.Model):
    customer = models.ForeignKey(
        "Customer", on_delete=models.SET_NULL, null=True, related_name="jobs"
    )
    ride = models.ForeignKey("Ride", on_delete=models.SET_NULL, null=True)
    job_date = models.DateField()
    job_start_date = models.DateField(auto_now_add=True)
    job_end_date = models.DateField(blank=True, null=True)
    last_updated_date = models.DateField(auto_now=True)
    light = models.ManyToManyField("Light", related_name="jobs", through="LightCount")

    def get_absolute_url(self):
        return reverse("detail_job", args=[str(self.id)])

    def __str__(self) -> str:
        return f"{self.customer.primary_contact}'s on {self.ride} start date: {self.job_start_date:%m-%d-%Y}"


class Customer(models.Model):
    company = models.CharField(max_length=50)
    primary_contact = models.CharField(max_length=50)
    primary_phone_number = models.CharField(max_length=50)
    email = models.EmailField(blank=True)

    def __str__(self) -> str:
        return self.primary_contact

    def get_absolute_url(self):
        return reverse("detail_customer", args=[str(self.id)])


class Ride(models.Model):
    ride_name = models.CharField(max_length=50)
    manufacturer = models.CharField(max_length=50)
    alternate_name = models.CharField(max_length=50, blank=True)
    customers = models.ManyToManyField("Customer", related_name="rides", blank=True)

    def __str__(self) -> str:
        return self.ride_name

    def get_absolute_url(self):
        return reverse("detail_ride", args=[str(self.id)])


class Light(models.Model):
    light_style = models.CharField(max_length=50)
    number_of_leds = models.PositiveIntegerField()

    def __str__(self) -> str:
        return f"{self.light_style} {self.number_of_leds}"

    def get_absolute_url(self):
        return reverse("list_lights")


class LightCount(models.Model):
    number_of_lights = models.PositiveIntegerField(null=True)
    light = models.ForeignKey(Light, on_delete=models.SET_NULL, null=True)
    job = models.ForeignKey(Job, on_delete=models.SET_NULL, null=True)

    def __str__(self) -> str:
        return f"{self.number_of_lights} {self.light}"


def job_directory_path(instance, filename):
    print("job_{0}/{1}".format(instance.job.job_date, filename))
    return "job_{0}/{1}".format(instance.job.job_date, filename)


class Image(models.Model):
    job = models.ForeignKey(
        Job, on_delete=models.SET_NULL, null=True, related_name="images"
    )
    image = models.ImageField(upload_to=job_directory_path)

    def get_absolute_url(self):
        return reverse("detail_customer", args=[str(self.job.id)])

jobs/forms.py
from django import forms
from django.forms import inlineformset_factory

# from dal.autocomplete import ModelSelect2
from .models import Customer, Job, Image, Ride

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class CustomerRideForm(forms.ModelForm):
    class Meta:
        model = Customer
        exclude = ("company", "primary_contact", "email", "primary_phone_number")

    rides = forms.ChoiceField(
        widget=forms.SelectMultiple,
        choices=[(choice.pk, choice) for choice in Ride.objects.all()],
    )


# class JobForm(forms.ModelForm):
#     class Meta:
#         model = Job
#         fields = "__all__"
#         widgets = {
#             "customer": ModelSelect2(
#                 url="autocomplete_customer",
#                 attrs={
#                     "data-html": True,
#                 },
#             ),
#             "light": forms.widgets.CheckboxSelectMultiple(),
#         }


class JobForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = "job_form"
        self.helper.form_method = "post"
        self.helper.form_action = "create_job"
        self.helper.add_input(Submit("submit", "Submit"))

    class Meta:
        model = Job
        fields = "__all__"

    # customer = forms.ChoiceField(
    #     choices=[(choice.pk, choice) for choice in Customer.objects.all()]
    # )


class JobUpdateForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = "__all__"


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = "__all__"


JobImageFormSet = inlineformset_factory(Job, Image, JobForm)

jobs/views.py
from django.urls import reverse_lazy
from django.views.generic.base import RedirectView
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.shortcuts import redirect, render
from django.core import serializers

from rest_framework import viewsets

from .serializers import JobSerializer
from .models import Job, Customer, Ride, Light, LightCount, Image
from .forms import CustomerRideForm, JobForm, ImageForm


class JobViewSet(viewsets.ModelViewSet):
    serializer_class = JobSerializer
    queryset = Job.objects.all()


class IndexView(RedirectView):
    url = reverse_lazy("list_jobs")


class JobDetailView(DetailView):
    model = Job
    context_object_name = "job"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        job_pk = self.kwargs.get(self.pk_url_kwarg)
        context["lights"] = LightCount.objects.filter(job__pk=job_pk)
        return context


class JobListView(ListView):
    model = Job
    context_object_name = "job_list"


class JobCreateView(CreateView):
    model = Job
    form_class = JobForm


class JobUpdateView(UpdateView):
    model = Job
    form_class = JobForm


class RideDetailView(DetailView):
    model = Ride


class RideCreateView(CreateView):
    model = Ride
    fields = "__all__"


class RideUpdateView(UpdateView):
    model = Ride
    fields = "__all__"


class RideListView(ListView):
    model = Ride
    context_object_name = "ride_list"


class CustomerDetailView(DetailView):
    model = Customer
    context_object_name = "customer"


class CustomerUpdateView(UpdateView):
    model = Customer
    fields = "__all__"

    def get_form_kwargs(self):
        """Return the keyword arguments for instantiating the form."""
        kwargs = super().get_form_kwargs()
        if hasattr(self, "object"):
            kwargs.update({"instance": self.object})
        return kwargs


class CustomerCreateView(CreateView):
    model = Customer
    fields = "__all__"


class CustomerListView(ListView):
    model = Customer
    context_object_name = "customer_list"


class LightDetailView(DetailView):
    model = Light


class LightCreateView(CreateView):
    model = Light
    fields = "__all__"


class LightUpdateView(UpdateView):
    model = Light


class LightListView(ListView):
    model = Light


class ImageCreateView(CreateView):
    model = Image
    form_class = ImageForm


def add_customer_rides(request, pk):
    customer = Customer.objects.get(pk=pk)
    form = CustomerRideForm()
    if request.method == "POST":
        form = CustomerRideForm(request.POST)
        rides = form.data.getlist("rides")
        if len(rides) > 0:
            for ride in rides:
                ride = Ride.objects.get(pk=int(ride))
                customer.rides.add(ride)
            return redirect(customer)

    rides = serializers.serialize("json", Ride.objects.all())
    return render(
        request, "jobs/customer_ride_form.html", {"form": form, "rides": rides}
    )

templates/jobs/customer_detail.html
{% extends "base.html" %}

{% block title %}{{ customer.primary_contact }}{% endblock %}

{% block content %}
<div class="row">
    <h3>{{ customer }}</h3>
    <div class="col-4">
        <h4>
            Rides
        </h4>
        <ul class="list-group list-group-flush">
            {% for ride in customer.rides.all %}
                <li class="list-group-item">{{ ride }}</li>
            {% endfor %}
        </ul>
    </div>
    <div class="col-4">
        <h4>Jobs</h4>
        <ul class="list-group list-group-flush">
            {% for job in customer.jobs.all %}
                <li class="list-group-item">
                    Work done on {{ job.ride }} started on {{ job.job_start_date }}
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

templates/jobs/customer_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}
<form class="g-2" method="POST">
    {% csrf_token %}
    <div class="row">
        <div class="col-4">
                <label for="{{ form.primary_contact.id_for_label }}" class="form-label"> Primary Contact:</label>
                {% render_field form.primary_contact class+="form-control" placeholder="Full Name"%}
        </div>
        <div class="col-4">
            <label for="{{ form.company.id_for_label }}" class="form-label"> Company Name:</label>
            {% render_field form.company class+="form-control" %}
        </div>
    </div>
    <div class="row">
        <!-- Hack to force columns onto next row! -->
        <div class="col-4">
            <label for="{{ form.email.id_for_label }}" class="form-label">Email</label>
            {% render_field form.email class+="form-control" %}
        </div>
        <div class="col-4">
            <label for="{{ form.primary_phone_number.id_for_label }}" class="form-label">Phone Number</label>
            {% render_field form.primary_phone_number|attr:"type:tel" class+="form-control" %}
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-sm-12 col-lg-2">
            <button type="submit" class="btn btn-block btn-primary">Submit</button>
        </div>
        {% if customer %}
        <div class="col-sm-12 col-lg-2">
            <a href="{% url 'add_customer_rides' pk=customer.id %}" class="btn btn-block btn-danger">
                Add Rides
            </a>
        </div>
        {% endif %}
    </div>
</form>
{% endblock %}

templates/jobs/customer_list.html
{% extends "base.html" %}
{% block title %}Customers{% endblock %}


{% block content %}
<div class="row">
    <div class="col-md-4">
        <h3 >Customers</h3>
        <div class="list-group list-group-flush">
            {% for customer in customer_list %}
            <a href="{{ customer.get_absolute_url }}" class="list-group-item list-group-item-action">{{ customer }}</a>
            {% endfor %}
        </div>
    </div>
    <div class="col-md-7">
        <div class="mt-2">
            <a class="text-reset" href="{% url 'create_customer' %}">Add Customer<i class="mx-1 fas fa-plus"></i></a>
        </div>
        {% for customer in customer_list %}
            <div class="row pt-1 mt-2">
                <div class="btn-group btn-group">
                    <a href="{% url 'detail_customer' customer.id %}"><button class="btn btn-primary mx-2">Details</button></a>
                    <a href="{% url 'update_customer' customer.id %}"><button class="btn btn-warning mx-2">Edit</button></a>
                    <!-- <a href=""><button class="btn btn-danger mx-1">Delete</button></a> -->
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/jobs/customer_ride_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}



{% block content %}
{% comment %} {{ ride }} {% endcomment %}
{% crispy form %}

   <button type="submit" class="btn mt-2 btn-primary">Submit</button>



{% endblock content %}

{% block javascript %}
<script>
    $(document).ready(function() {
    $('#id_rides').select2();

    $("button").click(function() {
           $("form").submit();
       });
});
</script>
{% endblock javascript %}

templates/jobs/image_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block content %}



<form enctype="multipart/form-data" action="/upload/"class="row g-2" method="POST">
    {% csrf_token %}
        <div class="col-6">
         <label for="{{ form.image.id_for_label }}" class="form-label">Images:</label>
            {% render_field form.image|append_attr:"multiple" class+="form-control" %}
        </div>
        <div class="col-6">
        <label for="{{ form.job.id_for_label }}" class="form-label">Job:</label><br>
            {% render_field form.job %}
        </div>
        <div class="col-12">
          <button type="submit" class="btn btn-primary">Submit</button>
      </div>
</form>

<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
{{ form.media }}

<script>
(function($) {
    $('#add-form').click(function() {
        var index = $('#id_inline_test_models-TOTAL_FORMS').val()
        var newTable = $('#id_inline_test_models-__prefix__-DELETE').parents('table').clone()
        newTable.find(':input').each(function() {
            for (attr of ['name', 'id'])
                $(this).attr(
                    attr,
                    $(this).attr(attr).replace('__prefix__', index)
                )
        })
        newTable.insertBefore($(this))
        $('#id_inline_test_models-TOTAL_FORMS').val(
            parseInt($('#id_inline_test_models-TOTAL_FORMS').val()) + 1
        )
        newTable.slideDown()
    })
})($)
</script>

{% endblock %}

templates/jobs/job_detail.html
{% extends "base.html" %}

{% block title %}{{ job.customer.primary_contact }}{% endblock %}


{% block content %}
<div class="row">
    <div class="col-3">
        <h4 class="mb-4">Details</h4>
        <ul class="list-group list-group-flush mt-1">
            <li class="list-group-item">{{ job }}</li>
            <li class="list-group-item">{{ job.ride }}</li>
            <li class="list-group-item">Start Date: {{ job.job_start_date }}</li>
            <li class="list-group-item">Finish Date: {{ job.job_end_date }}</li>
            <li class="list-group-item">Last Update: {{ job.last_updated_date }}</li>
        </ul>
    </div>

    <div class="col-7">
        <h4>Lights Types</h4>
        <div class="row">
            <div class="col-3">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Light Style</li>
                </ul>
            </div>
            <div class="col-1">
                <ul class="list-group list-group-flush">
                <li class="list-group-item">Quantity</li>
                </ul>
            </div>
        </div>
        <div class="row">

            <div class="col-3">
                <ul class="list-group list-group-flush">
                    {% for light in lights %}
                        <li class="list-group-item">{{ light.light  }}</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-1">
                <ul class="list-group list-group-flush">
                    {% for light in lights %}
                        <li class="list-group-item">
                            {{ light.number_of_lights }}
                        </li>
                    {% endfor %}
                </ul>
            </div>

        </div>
    </div>
</div>
<div class="row  justify-content-center">
    {% comment %} <div class="col-4 pt-2"><a href="{% url 'upload_image' job.id %}" class="btn btn-primary">Upload Images<i class="mx-2 fas fa-upload"></i></a></div> {% endcomment %}
</div>


{% endblock %}

templates/jobs/job_form.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}



{% crispy form form.helper %}

{% comment %} <form class="row g-2" method="POST">
    {% csrf_token %}
        <div class="col-4">
                <label for="{{ form.customer.id_for_label }}" class="form-label mb-3">Customer:</label><br>
                {{form.customer}}
        </div>
        <div class="col-4">
            <label for="{{ form.ride.id_for_label }}" class="form-label">Ride:</label>
            {% render_field form.ride class+="form-select" %}
        </div>
        <!-- Hack to force columns onto next row! -->
        <div class="w-100"></div>
        <div class="col-4">
            <label for="{{ form.light.id_for_label }}" class="form-check-label">Lights: </label>
            {% render_field form.light class+="" %}
        </div>
        <div class="col-4">
            <label for="{{ form.primary_phone_number.id_for_label }}" class="form-label">Phone Number</label>
            {% render_field form.primary_phone_number|attr:"type:tel" class+="form-control" %}
        </div>
        <div class="col-12">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
</form> {% endcomment %}

{% comment %} <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>

{{ form.media }}

{% block javascript %}
<script src="{% static 'js/jquery-file-upload/vendor/jquery.ui.widget.js' %}"></script>
<script src="{% static 'js/jquery-file-upload/jquery.iframe-transport.js' %}"></script>
<script src="{% static 'js/jquery-file-upload/jquery.fileupload.js' %}"></script>

<script>
    (function($) {
        $('#add-form').click(function() {
            var index = $('#id_inline_test_models-TOTAL_FORMS').val()
            var newTable = $('#id_inline_test_models-__prefix__-DELETE').parents('table').clone()
            newTable.find(':input').each(function() {
                for (attr of ['name', 'id'])
                    $(this).attr(
                        attr,
                        $(this).attr(attr).replace('__prefix__', index)
                    )
            })
            newTable.insertBefore($(this))
            $('#id_inline_test_models-TOTAL_FORMS').val(
                parseInt($('#id_inline_test_models-TOTAL_FORMS').val()) + 1
            )
            newTable.slideDown()
        })
    })($)
    </script>
{% endblock %} {% endcomment %}

{% endblock content %}

{% block javascript %}
<script>
    $(document).ready(function() {
    $('#id_customer').select2();
    $('#id_ride').select2();

    $("button").click(function() {
           $("form").submit();
       });
    $('#id_job_date').datepicker({
    format: 'mm/dd/yyyy',
    orientation: 'bottom'
    });
    $('#id_job_end_date').datepicker({
    format: 'mm/dd/yyyy',
    orientation: 'bottom'
    });
});
</script>
{% endblock javascript %}

templates/jobs/job_list.html
{% extends "base.html" %}
{% block title %}Home Page{% endblock %}


{% block content %}
<div class="row">
    <div class="col-md-4">
        <h3>Recent Jobs</h3>
        <div class="list-group list-group-flush">
            {% for job in job_list %}
            <a href="{{ job.get_absolute_url }}" class="list-group-item list-group-item-action">{{ job }}</a>
            {% endfor %}
        </div>
    </div>
    <div class="col-md-8">
        <div class="mt-2">
            <a class="text-reset" href="{% url 'create_job' %}">Add Job<i class="mx-1 fas fa-plus"></i></a>
        </div>
        {% for job in job_list %}
            <div class="row pt-1 mt-1">
                <div class="btn-group btn-group">
                    <a href="{% url 'detail_job' job.id %}"><button class="btn btn-primary mx-1">Details</button></a>
                    <a href="{% url 'update_job' job.id %}"><button class="btn btn-warning mx-1">Edit</button></a>
                <!-- <a href=""><button class="btn btn-danger mx-1">Delete</button></a> -->
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/jobs/light_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}
<form class="row g-2" method="POST">
    {% csrf_token %}
        <div class="col-4">
                <label for="{{ form.ride_name.id_for_label }}" class="form-label"> Light Style:</label>
                {% render_field form.light_style class+="form-control" placeholder=""%}
        </div>
        <div class="col-4">
            <label for="{{ form.manufacturer.id_for_label }}" class="form-label"> Number of LEDS:</label>
            {% render_field form.number_of_leds class+="form-control" %}
        </div>
        <!-- Hack to force columns onto next row! -->
        <!-- <div class="w-100"></div>
        <div class="col-4">
            <label for="{{ form.alternate_name.id_for_label }}" class="form-label">Alt Name:</label>
            {% render_field form.alternate_name class+="form-control" %}
        </div>
        <div class="col-4">
            <label for="{{ form.primary_phone_number.id_for_label }}" class="form-label">Phone Number</label>
            {% render_field form.primary_phone_number|attr:"type:tel" class+="form-control" %}
        </div> -->
        <div class="col-12">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
</form>
{% endblock %}

templates/jobs/light_list.html
{% extends "base.html" %}
{% block title %}Home Page{% endblock %}


{% block content %}
<div class="row">
    <div class="col-md-4">
        <h3>Lights</h3>
        <div class="list-group list-group-flush">
            {% for light in light_list %}
            <a href="{{ job.get_absolute_url }}" class="list-group-item list-group-item-action">{{ light }}</a>
            {% endfor %}
        </div>
    </div>
    <div class="col-md-8">
        <div class="d-flex align-items-center">
            <a class="pt-3 mx-2 text-reset" href="{% url 'create_light' %}">Add Light<i class="mx-1 fas fa-plus"></i></a>
        </div>
        {% for job in job_list %}
            <div class="row mt-1">
                <div class="btn-group btn-group">
                    <a href="{% url 'detail_job' job.id %}"><button class="btn btn-primary mx-1">Details</button></a>
                    <a href="{% url 'update_job' job.id %}"><button class="btn btn-warning mx-1">Edit</button></a>
                <!-- <a href=""><button class="btn btn-danger mx-1">Delete</button></a> -->
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/jobs/ride_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}


{% block content %}

{% csrf_token %}

{% crispy form%}






{% comment %} <form class="row g-2" method="POST">
    {% csrf_token %}
        <div class="col-4">
                <label for="{{ form.ride_name.id_for_label }}" class="form-label"> Ride Name:</label>
                {% render_field form.ride_name class+="form-control" placeholder="Ride Name"%}
        </div>
        <div class="col-4">
            <label for="{{ form.manufacturer.id_for_label }}" class="form-label"> Manufacturer:</label>
            {% render_field form.manufacturer class+="form-control" %}
        </div>
        <!-- Hack to force columns onto next row! -->
        <div class="w-100"></div>
        <div class="col-4">
            <label for="{{ form.alternate_name.id_for_label }}" class="form-label">Alt Name:</label>
            {% render_field form.alternate_name class+="form-control" %}
        </div>
        <div class="col-4">
            <label for="{{ form.primary_phone_number.id_for_label }}" class="form-label">Phone Number</label>
            {% render_field form.primary_phone_number|attr:"type:tel" class+="form-control" %}
        </div>
        <div class="col-12">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
</form> {% endcomment %}
{% endblock %}

templates/jobs/ride_list.html
{% extends "base.html" %}
{% block title %}Home Page{% endblock %}


{% block content %}
<div class="row">
    <div class="col-md-4">
        <h3>Rides</h3>
        <div class="list-group list-group-flush">
            {% for ride in ride_list %}
            <a href="{{ ride.get_absolute_url }}" class="list-group-item list-group-item-action">{{ ride }}</a>
            {% endfor %}
        </div>
    </div>
    <div class="col-md-8">
        <div class="mt-2">
            <a class="text-reset" href="{% url 'create_ride' %}">Add Ride<i class="mx-1 fas fa-plus"></i></a>
        </div>
        {% for ride in ride_list %}
            <div class="row pt-1 mt-2">
                <div class="btn-group btn-group">
                    <a href="{% url 'detail_ride' ride.id %}"><button class="btn btn-primary mx-1">Details</button></a>
                    <a href="{% url 'update_ride' ride.id %}"><button class="btn btn-warning mx-1">Edit</button></a>
                <!-- <a href=""><button class="btn btn-danger mx-1">Delete</button></a> -->
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}